name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Wrangler
      run: npm install -g @cloudflare/wrangler

    - name: Authenticate Wrangler with Cloudflare
      run: wrangler login

    - name: Publish the Worker
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: wrangler publish --api-key $CF_API_TOKEN
